"""add_oauth_support

Revision ID: 5017a64c7985
Revises: 759cf5b6ef5f
Create Date: 2026-06-23 18:24:39.731530
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import pgvector.sqlalchemy


# revision identifiers, used by Alembic.
revision: str = '5017a64c7985'
down_revision: Union[str, None] = '759cf5b6ef5f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'site_settings', ['id'])
    op.add_column('users', sa.Column('oauth_provider', sa.String(length=20), nullable=True))
    op.alter_column('users', 'hashed_password',
               existing_type=sa.VARCHAR(length=255),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'hashed_password',
               existing_type=sa.VARCHAR(length=255),
               nullable=False)
    op.drop_column('users', 'oauth_provider')
    op.drop_constraint(None, 'site_settings', type_='unique')
    # ### end Alembic commands ###