"""llm-db-schema

Revision ID: 759cf5b6ef5f
Revises: 46bf1bd55940
Create Date: 2026-06-10 23:02:26.735459
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import pgvector.sqlalchemy


# revision identifiers, used by Alembic.
revision: str = '759cf5b6ef5f'
down_revision: Union[str, None] = '46bf1bd55940'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('site_settings',
    sa.Column('site_name', sa.String(length=100), nullable=False),
    sa.Column('site_logo_url', sa.String(length=255), nullable=False),
    sa.Column('favicon_url', sa.String(length=255), nullable=True),
    sa.Column('login_img_url', sa.String(length=255), nullable=False),
    sa.Column('hero_img_url', sa.String(length=255), nullable=True),
    sa.Column('hero_video_url', sa.String(length=255), nullable=True),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id')
    )
    op.create_unique_constraint(None, 'categories', ['id'])
    op.create_unique_constraint(None, 'chat_messages', ['id'])
    op.create_unique_constraint(None, 'chat_sessions', ['id'])
    op.create_unique_constraint(None, 'order_items', ['id'])
    op.create_unique_constraint(None, 'orders', ['id'])
    op.create_unique_constraint(None, 'product_images', ['id'])
    op.create_unique_constraint(None, 'products', ['id'])
    op.create_unique_constraint(None, 'user_addresses', ['id'])
    op.create_unique_constraint(None, 'users', ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'users', type_='unique')
    op.drop_constraint(None, 'user_addresses', type_='unique')
    op.drop_constraint(None, 'products', type_='unique')
    op.drop_constraint(None, 'product_images', type_='unique')
    op.drop_constraint(None, 'orders', type_='unique')
    op.drop_constraint(None, 'order_items', type_='unique')
    op.drop_constraint(None, 'chat_sessions', type_='unique')
    op.drop_constraint(None, 'chat_messages', type_='unique')
    op.drop_constraint(None, 'categories', type_='unique')
    op.drop_table('site_settings')
    # ### end Alembic commands ###